In [2]:
from datascience import *
import numpy as np

**Reminder from Lab02**

`np.arange(start, stop, step)` produces an array with all the numbers starting at `start` and counting up by `step`, stopping **before** `stop` is reached
* If `step` is a positive value, Python checks if each element is `< end` before adding it to the resulting array.
* If `step` is a negative value, Python checks if each element is `> end` before adding it to the resulting array.

`arange` begins assembling the resulting array by following these steps:\n",
> 1. if `start < end`, then add `start` to the array (at the position `[0]`); otherwise, Python won't add anything and return **an empty array** `[]`.
> 1. after `start` is added to the array, the next element (at the position `[1]` in the array) is `start + step`, or more accurately, `step` added to the previous element in the array;
> 1. if the resulting new value passes the comparison with the `end`, then this value is included in the resulting array, otherwise, the process stops and the resutling array is returned.
> 1. for each element `n` in the array, its value is obtained by adding `step` to the previous element `n-1` in the array and comparing it to `end`.

For example, the value of `np.arange(1, 8, 2)` is an array with elements 1, 3, 5 and 7 -- it starts at 1 and counts up by 2, then stops before 8.  In other words, it's equivalent to `make_array(1, 3, 5, 7)`."
   

**Check-in Quiz from Lecture**

In [4]:
x = make_array(2, 3, 4)
y = np.arange(2, 3, 4)
z = np.arange(3)

array([0, 1, 2])

In [5]:
x

array([2, 3, 4])

In [6]:
y

array([2])

In [7]:
z

array([0, 1, 2])

In [8]:
print("x =", x)
print("y =", y)
print("z =", z)

x = [2 3 4]
y = [2]
z = [0 1 2]


In [10]:
x + y

array([4, 5, 6])

In [11]:
x + 2 # same as above, since y has only one element stored in it

array([4, 5, 6])

In [9]:
x + z

array([2, 4, 6])

In [12]:
x.item(0) + y.item(0)

4

In [13]:
x.item(1) + y.item(1)

IndexError: index 1 is out of bounds for axis 0 with size 1

Let's produce arrays that all start with 5 as the first item/element and only have 2 elements in the resulting array.

In [14]:
a = np.arange(5, 8, 2) # 5, 7, 9 < 8 --> False, so 9 is not added
print("a =", a)
b = np.arange(5, 7, 1)
print("b =", b)
c = np.arange(5, 15, 5)
print("c =", c)
d = np.arange(5, 9, 2)
print("d =", d)
e = np.arange(5, -4, -5)
print("e =", e)

a = [5 7]
b = [5 6]
c = [ 5 10]
d = [5 7]
e = [5 0]


In [ ]:
(5, 8, 2)
# start at 5
# stop before 8
# step = 2, every element in the array is separated by 2

(5, 7, 1)
# start at 5
# stop before 7


5, 15, 5
# start at 5
# stop before 15

5, 9, 2
# start at 5

(5, -4, -5)
# start at 5
# stop before -4
# step = -5, so every element in the array is separated by -5
# (copy/pasting during lecture accidentally (incorrectly) left the step as -2)

In [17]:
result = np.arange(5, 15, -2)
result

array([], dtype=int64)

In [20]:
result = make_array() # we are not adding any elements/items

In [21]:
result # we now have an "empty array" that is represented by []

array([], dtype=float64)

In [22]:
result.item(0) # since the array is empty, trying to retrieve the first item won't work

IndexError: index 0 is out of bounds for axis 0 with size 0