In [27]:
import numpy as np
from datascience import *

In [24]:
np.random.random()

0.8953101431135632

In [28]:
groups = make_array('treatment', 'control')

In [29]:
groups

array(['treatment', 'control'], dtype='<U9')

In [64]:
assignment = np.random.choice(groups, 100)

In [65]:
assignment

array(['control', 'control', 'treatment', 'treatment', 'control',
       'control', 'treatment', 'treatment', 'control', 'treatment',
       'treatment', 'control', 'treatment', 'control', 'control',
       'control', 'control', 'control', 'control', 'treatment',
       'treatment', 'treatment', 'control', 'treatment', 'control',
       'treatment', 'treatment', 'control', 'treatment', 'control',
       'control', 'treatment', 'treatment', 'treatment', 'control',
       'control', 'control', 'treatment', 'treatment', 'treatment',
       'treatment', 'treatment', 'control', 'control', 'control',
       'control', 'control', 'treatment', 'treatment', 'control',
       'treatment', 'treatment', 'treatment', 'treatment', 'control',
       'control', 'control', 'treatment', 'treatment', 'treatment',
       'treatment', 'treatment', 'treatment', 'control', 'treatment',
       'treatment', 'treatment', 'control', 'control', 'control',
       'control', 'treatment', 'control', 'control', 'cont

In [48]:
num = np.arange(10, 20, 3)
num

array([10, 13, 16, 19])

In [49]:
num * 10

array([100, 130, 160, 190])

In [51]:
num / 2

array([5. , 6.5, 8. , 9.5])

In [52]:
num == 16

array([False, False,  True, False])

In [53]:
num > 10

array([False,  True,  True,  True])

In [54]:
num

array([10, 13, 16, 19])

In [55]:
num < 16

array([ True,  True, False, False])

In [56]:
assignment

array(['control', 'treatment', 'treatment', 'treatment', 'treatment',
       'control', 'control', 'treatment', 'treatment', 'control'],
      dtype='<U9')

In [58]:
assignment == 'control'

array([ True, False, False, False, False,  True,  True, False, False,
        True])

In [66]:
np.count_nonzero(assignment == 'control')

53

In [60]:
int(True)

1

In [61]:
int(False)

0

In [67]:
np.count_nonzero(assignment == 'treatment')

47